# Generated by Django 5.0.3 on 2024-04-16 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentName', models.CharField(max_length=50)),
                ('fatherName', models.CharField(max_length=50)),
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('programme', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('mobilenumber', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('aadharnumber', models.IntegerField()),
                ('marksheetcopy', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), django.core.validators.MaxValueValidator(51200)])),
                ('aadharcopy', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), django.core.validators.MaxValueValidator(51200)])),
            ],
        ),
    ]
