# Generated by Django 5.0.3 on 2024-04-16 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_created_at_student_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Certificate',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
